- name: SPP password lookup (system+username)
  hosts: localhost
  gather_facts: false

  vars:
    host: ""
    cert: ""
    key: ""
    cacert: ""
    system: ""          # e.g. CSDevExtDomain
    account: ""         # e.g. svc.aap_spe_win
    spp_registration_index: 0

  tasks:
    - name: Build a2a connection dict
      set_fact:
        a2apasswordconnectioninfo:
          spp_appliance: "{{ host }}"
          spp_certificate_file: "{{ cert }}"
          spp_certificate_key: "{{ key }}"
          spp_tls_cert: "{{ cacert }}"
          spp_credential_type: password
          spp_validate_certs: true

    - name: Retrieve password via discovery (ApiKey derived from system+username)
      set_fact:
        my_password: >-
          {{
            lookup(
              'oneidentity.safeguardcollection.safeguardcredentials',
              '',  # empty positional ApiKey triggers discovery
              a2aconnection=a2apasswordconnectioninfo,
              spp_systemname=system,
              spp_username=account,
              spp_registration_index=spp_registration_index
            )
          }}
      no_log: true

    - debug:
        msg: "Password retrieved into variable 'my_password'."
