---
# get_safeguard_password.yml
# Designed for AAP with the custom “Safeguard Credential” type shown in your screenshots.
# It consumes ONLY the injected vars/files from that credential type.

- name: Get password from Safeguard (API key or system+account)
  hosts: localhost
  gather_facts: false

  # The following vars are injected by your AAP “Safeguard Credential”:
  #   spp_appliance            (string)
  #   spp_api_key              (string; may be empty)
  #   spp_system_name          (string; used when spp_api_key is empty)
  #   spp_account_name         (string; used when spp_api_key is empty)
  #   spp_credential_type      (string: password|privatekey)  # vendor choices
  #   spp_catrust_path         (path to CA bundle PEM; file created by injector)
  #   spp_public_key_path      (path to client CERT .pem; file created by injector)
  #   spp_private_key_path     (path to client KEY  .pem; file created by injector)

  vars:
    # Default if your credential type doesn’t define it:
    spp_validate_certs: true
    # Optional: choose non-zero registration index if needed
    spp_registration_index: 0

  tasks:
    - name: Sanity check required injected fields
      assert:
        that:
          - spp_appliance | length > 0
          - spp_public_key_path | length > 0
          - spp_private_key_path | length > 0
          - spp_catrust_path | length > 0
          - spp_credential_type | lower in ['password','privatekey']
        fail_msg: "Missing or invalid Safeguard injected inputs."

    - name: Build a2a connection dict for the lookup plugin (vendor spp_* keys)
      set_fact:
        a2apasswordconnectioninfo:
          spp_appliance: "{{ spp_appliance }}"
          spp_certificate_file: "{{ spp_public_key_path }}"
          spp_certificate_key: "{{ spp_private_key_path }}"
          spp_tls_cert: "{{ spp_catrust_path }}"
          spp_credential_type: "{{ spp_credential_type | lower }}"
          spp_validate_certs: "{{ spp_validate_certs }}"

    - name: Retrieve password (API key if provided; else discover via system+account)
      set_fact:
        spp_password: >-
          {{
            lookup(
              'oneidentity.safeguardcollection.safeguardcredentials',
              (spp_api_key | default('')),
              a2aconnection=a2apasswordconnectioninfo,
              spp_systemname=(spp_system_name if (spp_api_key | default('')) | length == 0 else omit),
              spp_username=(spp_account_name if (spp_api_key | default('')) | length == 0 else omit),
              spp_registration_index=(spp_registration_index if (spp_api_key | default('')) | length == 0 else omit)
            )
          }}
      no_log: true

    - name: Confirm retrieval (value hidden)
      debug:
        msg: "Password retrieved and stored in variable 'spp_password'."
      no_log: true
